"""inital schema

Revision ID: a69293a42446
Revises: 
Create Date: 2026-04-27 16:35:35.870622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a69293a42446'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line1', sa.String(length=200), nullable=False),
    sa.Column('line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_addresses')),
    schema='invoice_importer'
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['invoice_importer.addresses.id'], name=op.f('fk_vendors_address_id_addresses'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors')),
    sa.UniqueConstraint('address_id', name=op.f('uq_vendors_address_id')),
    schema='invoice_importer'
    )
    op.create_index(op.f('ix_invoice_importer_vendors_name'), 'vendors', ['name'], unique=True, schema='invoice_importer')
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('source_identifier', sa.String(length=500), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['invoice_importer.vendors.id'], name=op.f('fk_invoices_vendor_id_vendors'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('content_hash', name=op.f('uq_invoices_content_hash')),
    sa.UniqueConstraint('vendor_id', 'invoice_number', name='uq_vendor_invoice'),
    schema='invoice_importer'
    )
    op.create_index(op.f('ix_invoice_importer_invoices_vendor_id'), 'invoices', ['vendor_id'], unique=False, schema='invoice_importer')
    op.create_table('invoice_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=19, scale=5), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=19, scale=5), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice_importer.invoices.id'], name=op.f('fk_invoice_line_items_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_line_items')),
    sa.UniqueConstraint('invoice_id', 'line_number', name='uq_invoice_line_item'),
    schema='invoice_importer'
    )
    op.create_index(op.f('ix_invoice_importer_invoice_line_items_invoice_id'), 'invoice_line_items', ['invoice_id'], unique=False, schema='invoice_importer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_importer_invoice_line_items_invoice_id'), table_name='invoice_line_items', schema='invoice_importer')
    op.drop_table('invoice_line_items', schema='invoice_importer')
    op.drop_index(op.f('ix_invoice_importer_invoices_vendor_id'), table_name='invoices', schema='invoice_importer')
    op.drop_table('invoices', schema='invoice_importer')
    op.drop_index(op.f('ix_invoice_importer_vendors_name'), table_name='vendors', schema='invoice_importer')
    op.drop_table('vendors', schema='invoice_importer')
    op.drop_table('addresses', schema='invoice_importer')
    # ### end Alembic commands ###
